### ISSUE TITLE
Conflict with BuddyDev's "Auto Activate & login Redirect To Profile On Signup"

### ISSUE THREAD

**Issue by shay1383** [sheabunge/bp-security-check#8]
Hi Shea
First of, thank you for your awesome plugin.

The conflict I'm facing is between "[Auto Activate & login Redirect To Profile On Signup](https://buddydev.com/plugins/bp-auto-activate-auto-login/)" and "BP Security Check" when both activated.

Normally, BP auto activate & login plugin login every user after he finished registering, and forwarding him to his profile.
But when Security Check is activated it doesn't login at all after registering.

Please help me with that,
And thank you for your time,
Shay.

**Comment by sheabunge** [comment]
Sure! I'll take a look at the other plugin and see what the conflict could be.

**Comment by shay1383** [comment]
Thank you so much!

**Comment by shay1383** [comment]
Let me know when you find anything :)

**Comment by shay1383** [comment]
Is there any update Shea?

**Comment by sheabunge** [comment]
I realise it's been a while, but don't worry, I'm still working on finding a solution. I'll let you know as soon as I do.

**Comment by sheabunge** [comment]
I've been trying this out, and this plugin seems to be working as expected for me when both are activated. I'm wondering whether this could be due to a different conflict on your site?

**Comment by shay1383** [comment]
No It's not an issue in my site because I've created a new site to test the conflict
It's seems to work until you enable security check on login page, via security check settings

**Comment by sheabunge** [comment]
Thank you very much for that extra piece of information - it's a bit silly of me to miss something so obvious.

I've managed to sort out what the issue is, and create a patch. It'll be included in version 3.2.2, which I am just releasing now.

Thank you for reporting this, and my apologies for taking so long to fix it. I really appreciate you narrowing down the issue, and confirming on a new site, and passing on a copy of the plugin for me to test with.

**Comment by shay1383** [comment]
Thank you very much for caring and for fixing it.
Keep making awesome plugins :)
